name: Update release with changelog
on:
  release:
    types: [created]

jobs:
  update-release-body:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Update changelog
        uses: ./
        with:
          update_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
