name: Build and test
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - "master"
      - "releases/*"

jobs:
  build: # Make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: |
          npm ci
      - run: |
          npm run all
  test: # Make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate changelog
        uses: ./
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display output
        run: echo "${{ steps.changelog.outputs.message }}"
